package org.example.jfinal.demo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTest<M extends BaseTest<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setC1(java.lang.String c1) {
		set("c1", c1);
	}
	
	public java.lang.String getC1() {
		return getStr("c1");
	}
	
	public void setC2(java.lang.String c2) {
		set("c2", c2);
	}
	
	public java.lang.String getC2() {
		return getStr("c2");
	}
	
	public void setC3(java.lang.String c3) {
		set("c3", c3);
	}
	
	public java.lang.String getC3() {
		return getStr("c3");
	}
	
}
