package org.example.jfinal.demo.model;

import org.example.jfinal.demo.model.base.BaseArticle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Article extends BaseArticle<Article> {
	
}
