package org.example.jfinal.demo.model;

import org.example.jfinal.demo.model.base.BaseTest;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Test extends BaseTest<Test> {
	
}
