package org.example.jfinal.demo.model;

import org.example.jfinal.demo.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	
}
