# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
  port: 30087

spring:
  shardingsphere:
    datasource:
      names: master
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url:  jdbc:mysql://localhost:3306/ds_0?serverTimezone=Hongkong
        username: root
        password: 123456789

    sharding:
      tables:
        user:
          actual-data-nodes: master.user_${0..3}
          table-strategy:
            standard:
              sharding-column: id
              precise-algorithm-class-name: org.example.sharding.demo.config.MyPreciseShardingAlgorithm

