# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
  port: 30087

spring:
  shardingsphere:
    datasource:
      names: master
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url:  jdbc:mysql://localhost:3306/ds_0?serverTimezone=Hongkong
        username: root
        password: 123456789
        initial-size: 20
        min-idle: 20
        maxActive: 100
        filters: log4j2
    sharding:
      tables:
        person_attence:
          actual-data-nodes: master.person_attence_${202001..202012}
          table-strategy:
            standard:
              sharding-column: attence_time
              precise-algorithm-class-name: org.example.sharding.demo.config.DatePreciseShardingAlgorithm
              range-algorithm-class-name: org.example.sharding.demo.config.DatePreciseShardingAlgorithm

    props:
      sql.show: true
      max.connections.size.per.query: 12

